# Generated by Django 2.2.4 on 2019-10-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
