# Generated by Django 2.2.4 on 2019-10-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
